//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace SecVizAdminApp.CorrelationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CorrelationServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CorrelationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetFullAttackGraphDotFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttackGraphDotFileWithAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFullAttackGraphOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAttackGraphWithAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PredictNextAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PredictNextAlertsForAlertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CorrelationService() {
            this.Url = global::SecVizAdminApp.Properties.Settings.Default.SecVizUserControl_CorrelationService_CorrelationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetFullAttackGraphDotFileCompletedEventHandler GetFullAttackGraphDotFileCompleted;
        
        /// <remarks/>
        public event GetAttackGraphDotFileWithAttributesCompletedEventHandler GetAttackGraphDotFileWithAttributesCompleted;
        
        /// <remarks/>
        public event GetFullAttackGraphCompletedEventHandler GetFullAttackGraphCompleted;
        
        /// <remarks/>
        public event GetAttackGraphWithAttributesCompletedEventHandler GetAttackGraphWithAttributesCompleted;
        
        /// <remarks/>
        public event PredictNextAlertsCompletedEventHandler PredictNextAlertsCompleted;
        
        /// <remarks/>
        public event PredictNextAlertsForAlertCompletedEventHandler PredictNextAlertsForAlertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFullAttackGraphDotFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetFullAttackGraphDotFile() {
            object[] results = this.Invoke("GetFullAttackGraphDotFile", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFullAttackGraphDotFileAsync() {
            this.GetFullAttackGraphDotFileAsync(null);
        }
        
        /// <remarks/>
        public void GetFullAttackGraphDotFileAsync(object userState) {
            if ((this.GetFullAttackGraphDotFileOperationCompleted == null)) {
                this.GetFullAttackGraphDotFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullAttackGraphDotFileOperationCompleted);
            }
            this.InvokeAsync("GetFullAttackGraphDotFile", new object[0], this.GetFullAttackGraphDotFileOperationCompleted, userState);
        }
        
        private void OnGetFullAttackGraphDotFileOperationCompleted(object arg) {
            if ((this.GetFullAttackGraphDotFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullAttackGraphDotFileCompleted(this, new GetFullAttackGraphDotFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttackGraphDotFileWithAttributes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAttackGraphDotFileWithAttributes(AttributeValueList attrs) {
            object[] results = this.Invoke("GetAttackGraphDotFileWithAttributes", new object[] {
                        attrs});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAttackGraphDotFileWithAttributesAsync(AttributeValueList attrs) {
            this.GetAttackGraphDotFileWithAttributesAsync(attrs, null);
        }
        
        /// <remarks/>
        public void GetAttackGraphDotFileWithAttributesAsync(AttributeValueList attrs, object userState) {
            if ((this.GetAttackGraphDotFileWithAttributesOperationCompleted == null)) {
                this.GetAttackGraphDotFileWithAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttackGraphDotFileWithAttributesOperationCompleted);
            }
            this.InvokeAsync("GetAttackGraphDotFileWithAttributes", new object[] {
                        attrs}, this.GetAttackGraphDotFileWithAttributesOperationCompleted, userState);
        }
        
        private void OnGetAttackGraphDotFileWithAttributesOperationCompleted(object arg) {
            if ((this.GetAttackGraphDotFileWithAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttackGraphDotFileWithAttributesCompleted(this, new GetAttackGraphDotFileWithAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFullAttackGraph", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFullAttackGraph() {
            object[] results = this.Invoke("GetFullAttackGraph", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFullAttackGraphAsync() {
            this.GetFullAttackGraphAsync(null);
        }
        
        /// <remarks/>
        public void GetFullAttackGraphAsync(object userState) {
            if ((this.GetFullAttackGraphOperationCompleted == null)) {
                this.GetFullAttackGraphOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullAttackGraphOperationCompleted);
            }
            this.InvokeAsync("GetFullAttackGraph", new object[0], this.GetFullAttackGraphOperationCompleted, userState);
        }
        
        private void OnGetFullAttackGraphOperationCompleted(object arg) {
            if ((this.GetFullAttackGraphCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullAttackGraphCompleted(this, new GetFullAttackGraphCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAttackGraphWithAttributes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAttackGraphWithAttributes(AttributeValueList atttrs) {
            object[] results = this.Invoke("GetAttackGraphWithAttributes", new object[] {
                        atttrs});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAttackGraphWithAttributesAsync(AttributeValueList atttrs) {
            this.GetAttackGraphWithAttributesAsync(atttrs, null);
        }
        
        /// <remarks/>
        public void GetAttackGraphWithAttributesAsync(AttributeValueList atttrs, object userState) {
            if ((this.GetAttackGraphWithAttributesOperationCompleted == null)) {
                this.GetAttackGraphWithAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAttackGraphWithAttributesOperationCompleted);
            }
            this.InvokeAsync("GetAttackGraphWithAttributes", new object[] {
                        atttrs}, this.GetAttackGraphWithAttributesOperationCompleted, userState);
        }
        
        private void OnGetAttackGraphWithAttributesOperationCompleted(object arg) {
            if ((this.GetAttackGraphWithAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAttackGraphWithAttributesCompleted(this, new GetAttackGraphWithAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PredictNextAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PredictNextAlerts() {
            object[] results = this.Invoke("PredictNextAlerts", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PredictNextAlertsAsync() {
            this.PredictNextAlertsAsync(null);
        }
        
        /// <remarks/>
        public void PredictNextAlertsAsync(object userState) {
            if ((this.PredictNextAlertsOperationCompleted == null)) {
                this.PredictNextAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPredictNextAlertsOperationCompleted);
            }
            this.InvokeAsync("PredictNextAlerts", new object[0], this.PredictNextAlertsOperationCompleted, userState);
        }
        
        private void OnPredictNextAlertsOperationCompleted(object arg) {
            if ((this.PredictNextAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PredictNextAlertsCompleted(this, new PredictNextAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PredictNextAlertsForAlert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] PredictNextAlertsForAlert(string alertId) {
            object[] results = this.Invoke("PredictNextAlertsForAlert", new object[] {
                        alertId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void PredictNextAlertsForAlertAsync(string alertId) {
            this.PredictNextAlertsForAlertAsync(alertId, null);
        }
        
        /// <remarks/>
        public void PredictNextAlertsForAlertAsync(string alertId, object userState) {
            if ((this.PredictNextAlertsForAlertOperationCompleted == null)) {
                this.PredictNextAlertsForAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPredictNextAlertsForAlertOperationCompleted);
            }
            this.InvokeAsync("PredictNextAlertsForAlert", new object[] {
                        alertId}, this.PredictNextAlertsForAlertOperationCompleted, userState);
        }
        
        private void OnPredictNextAlertsForAlertOperationCompleted(object arg) {
            if ((this.PredictNextAlertsForAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PredictNextAlertsForAlertCompleted(this, new PredictNextAlertsForAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AttributeValueList {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFullAttackGraphDotFileCompletedEventHandler(object sender, GetFullAttackGraphDotFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullAttackGraphDotFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullAttackGraphDotFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAttackGraphDotFileWithAttributesCompletedEventHandler(object sender, GetAttackGraphDotFileWithAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttackGraphDotFileWithAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttackGraphDotFileWithAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFullAttackGraphCompletedEventHandler(object sender, GetFullAttackGraphCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullAttackGraphCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFullAttackGraphCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAttackGraphWithAttributesCompletedEventHandler(object sender, GetAttackGraphWithAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAttackGraphWithAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAttackGraphWithAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PredictNextAlertsCompletedEventHandler(object sender, PredictNextAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PredictNextAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PredictNextAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PredictNextAlertsForAlertCompletedEventHandler(object sender, PredictNextAlertsForAlertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PredictNextAlertsForAlertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PredictNextAlertsForAlertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591