//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace SecVizAdminApp.ServerMonitorService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServerMonitorServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ServerMonitorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ScanServerVulnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRawAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAlertsWithinIntervalOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServerNetworkTrafficOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKBPredicatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKBHyperAlertTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKBImplicationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHyperAlertTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddHyperAlertTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddImplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPredicateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewAlertOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServerMonitorService() {
            this.Url = global::SecVizAdminApp.Properties.Settings.Default.SecVizUserControl_MonitorWebRef_ServerMonitorService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ScanServerVulnCompletedEventHandler ScanServerVulnCompleted;
        
        /// <remarks/>
        public event GetRawAlertsCompletedEventHandler GetRawAlertsCompleted;
        
        /// <remarks/>
        public event GetAlertsWithinIntervalCompletedEventHandler GetAlertsWithinIntervalCompleted;
        
        /// <remarks/>
        public event GetServerNetworkTrafficCompletedEventHandler GetServerNetworkTrafficCompleted;
        
        /// <remarks/>
        public event GetKBPredicatesCompletedEventHandler GetKBPredicatesCompleted;
        
        /// <remarks/>
        public event GetKBHyperAlertTypesCompletedEventHandler GetKBHyperAlertTypesCompleted;
        
        /// <remarks/>
        public event GetKBImplicationsCompletedEventHandler GetKBImplicationsCompleted;
        
        /// <remarks/>
        public event GetHyperAlertTypeCompletedEventHandler GetHyperAlertTypeCompleted;
        
        /// <remarks/>
        public event AddHyperAlertTypeCompletedEventHandler AddHyperAlertTypeCompleted;
        
        /// <remarks/>
        public event AddImplicationCompletedEventHandler AddImplicationCompleted;
        
        /// <remarks/>
        public event AddPredicateCompletedEventHandler AddPredicateCompleted;
        
        /// <remarks/>
        public event AddNewAlertCompletedEventHandler AddNewAlertCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ScanServerVuln", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vulnerability[] ScanServerVuln() {
            object[] results = this.Invoke("ScanServerVuln", new object[0]);
            return ((Vulnerability[])(results[0]));
        }
        
        /// <remarks/>
        public void ScanServerVulnAsync() {
            this.ScanServerVulnAsync(null);
        }
        
        /// <remarks/>
        public void ScanServerVulnAsync(object userState) {
            if ((this.ScanServerVulnOperationCompleted == null)) {
                this.ScanServerVulnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnScanServerVulnOperationCompleted);
            }
            this.InvokeAsync("ScanServerVuln", new object[0], this.ScanServerVulnOperationCompleted, userState);
        }
        
        private void OnScanServerVulnOperationCompleted(object arg) {
            if ((this.ScanServerVulnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ScanServerVulnCompleted(this, new ScanServerVulnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRawAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] GetRawAlerts() {
            object[] results = this.Invoke("GetRawAlerts", new object[0]);
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRawAlertsAsync() {
            this.GetRawAlertsAsync(null);
        }
        
        /// <remarks/>
        public void GetRawAlertsAsync(object userState) {
            if ((this.GetRawAlertsOperationCompleted == null)) {
                this.GetRawAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRawAlertsOperationCompleted);
            }
            this.InvokeAsync("GetRawAlerts", new object[0], this.GetRawAlertsOperationCompleted, userState);
        }
        
        private void OnGetRawAlertsOperationCompleted(object arg) {
            if ((this.GetRawAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRawAlertsCompleted(this, new GetRawAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAlertsWithinInterval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] GetAlertsWithinInterval(string start, string end) {
            object[] results = this.Invoke("GetAlertsWithinInterval", new object[] {
                        start,
                        end});
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAlertsWithinIntervalAsync(string start, string end) {
            this.GetAlertsWithinIntervalAsync(start, end, null);
        }
        
        /// <remarks/>
        public void GetAlertsWithinIntervalAsync(string start, string end, object userState) {
            if ((this.GetAlertsWithinIntervalOperationCompleted == null)) {
                this.GetAlertsWithinIntervalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAlertsWithinIntervalOperationCompleted);
            }
            this.InvokeAsync("GetAlertsWithinInterval", new object[] {
                        start,
                        end}, this.GetAlertsWithinIntervalOperationCompleted, userState);
        }
        
        private void OnGetAlertsWithinIntervalOperationCompleted(object arg) {
            if ((this.GetAlertsWithinIntervalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAlertsWithinIntervalCompleted(this, new GetAlertsWithinIntervalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetServerNetworkTraffic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetServerNetworkTraffic() {
            object[] results = this.Invoke("GetServerNetworkTraffic", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServerNetworkTrafficAsync() {
            this.GetServerNetworkTrafficAsync(null);
        }
        
        /// <remarks/>
        public void GetServerNetworkTrafficAsync(object userState) {
            if ((this.GetServerNetworkTrafficOperationCompleted == null)) {
                this.GetServerNetworkTrafficOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServerNetworkTrafficOperationCompleted);
            }
            this.InvokeAsync("GetServerNetworkTraffic", new object[0], this.GetServerNetworkTrafficOperationCompleted, userState);
        }
        
        private void OnGetServerNetworkTrafficOperationCompleted(object arg) {
            if ((this.GetServerNetworkTrafficCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServerNetworkTrafficCompleted(this, new GetServerNetworkTrafficCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKBPredicates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KBPredicate[] GetKBPredicates() {
            object[] results = this.Invoke("GetKBPredicates", new object[0]);
            return ((KBPredicate[])(results[0]));
        }
        
        /// <remarks/>
        public void GetKBPredicatesAsync() {
            this.GetKBPredicatesAsync(null);
        }
        
        /// <remarks/>
        public void GetKBPredicatesAsync(object userState) {
            if ((this.GetKBPredicatesOperationCompleted == null)) {
                this.GetKBPredicatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKBPredicatesOperationCompleted);
            }
            this.InvokeAsync("GetKBPredicates", new object[0], this.GetKBPredicatesOperationCompleted, userState);
        }
        
        private void OnGetKBPredicatesOperationCompleted(object arg) {
            if ((this.GetKBPredicatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKBPredicatesCompleted(this, new GetKBPredicatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKBHyperAlertTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KBHyperAlertType[] GetKBHyperAlertTypes() {
            object[] results = this.Invoke("GetKBHyperAlertTypes", new object[0]);
            return ((KBHyperAlertType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetKBHyperAlertTypesAsync() {
            this.GetKBHyperAlertTypesAsync(null);
        }
        
        /// <remarks/>
        public void GetKBHyperAlertTypesAsync(object userState) {
            if ((this.GetKBHyperAlertTypesOperationCompleted == null)) {
                this.GetKBHyperAlertTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKBHyperAlertTypesOperationCompleted);
            }
            this.InvokeAsync("GetKBHyperAlertTypes", new object[0], this.GetKBHyperAlertTypesOperationCompleted, userState);
        }
        
        private void OnGetKBHyperAlertTypesOperationCompleted(object arg) {
            if ((this.GetKBHyperAlertTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKBHyperAlertTypesCompleted(this, new GetKBHyperAlertTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetKBImplications", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KBImplication[] GetKBImplications() {
            object[] results = this.Invoke("GetKBImplications", new object[0]);
            return ((KBImplication[])(results[0]));
        }
        
        /// <remarks/>
        public void GetKBImplicationsAsync() {
            this.GetKBImplicationsAsync(null);
        }
        
        /// <remarks/>
        public void GetKBImplicationsAsync(object userState) {
            if ((this.GetKBImplicationsOperationCompleted == null)) {
                this.GetKBImplicationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKBImplicationsOperationCompleted);
            }
            this.InvokeAsync("GetKBImplications", new object[0], this.GetKBImplicationsOperationCompleted, userState);
        }
        
        private void OnGetKBImplicationsOperationCompleted(object arg) {
            if ((this.GetKBImplicationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKBImplicationsCompleted(this, new GetKBImplicationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHyperAlertType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KBHyperAlertType[] GetHyperAlertType(string[] hatname) {
            object[] results = this.Invoke("GetHyperAlertType", new object[] {
                        hatname});
            return ((KBHyperAlertType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetHyperAlertTypeAsync(string[] hatname) {
            this.GetHyperAlertTypeAsync(hatname, null);
        }
        
        /// <remarks/>
        public void GetHyperAlertTypeAsync(string[] hatname, object userState) {
            if ((this.GetHyperAlertTypeOperationCompleted == null)) {
                this.GetHyperAlertTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHyperAlertTypeOperationCompleted);
            }
            this.InvokeAsync("GetHyperAlertType", new object[] {
                        hatname}, this.GetHyperAlertTypeOperationCompleted, userState);
        }
        
        private void OnGetHyperAlertTypeOperationCompleted(object arg) {
            if ((this.GetHyperAlertTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHyperAlertTypeCompleted(this, new GetHyperAlertTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddHyperAlertType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddHyperAlertType(KBHyperAlertType hyperalert) {
            this.Invoke("AddHyperAlertType", new object[] {
                        hyperalert});
        }
        
        /// <remarks/>
        public void AddHyperAlertTypeAsync(KBHyperAlertType hyperalert) {
            this.AddHyperAlertTypeAsync(hyperalert, null);
        }
        
        /// <remarks/>
        public void AddHyperAlertTypeAsync(KBHyperAlertType hyperalert, object userState) {
            if ((this.AddHyperAlertTypeOperationCompleted == null)) {
                this.AddHyperAlertTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddHyperAlertTypeOperationCompleted);
            }
            this.InvokeAsync("AddHyperAlertType", new object[] {
                        hyperalert}, this.AddHyperAlertTypeOperationCompleted, userState);
        }
        
        private void OnAddHyperAlertTypeOperationCompleted(object arg) {
            if ((this.AddHyperAlertTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddHyperAlertTypeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddImplication", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddImplication(KBImplication implication) {
            this.Invoke("AddImplication", new object[] {
                        implication});
        }
        
        /// <remarks/>
        public void AddImplicationAsync(KBImplication implication) {
            this.AddImplicationAsync(implication, null);
        }
        
        /// <remarks/>
        public void AddImplicationAsync(KBImplication implication, object userState) {
            if ((this.AddImplicationOperationCompleted == null)) {
                this.AddImplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddImplicationOperationCompleted);
            }
            this.InvokeAsync("AddImplication", new object[] {
                        implication}, this.AddImplicationOperationCompleted, userState);
        }
        
        private void OnAddImplicationOperationCompleted(object arg) {
            if ((this.AddImplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddImplicationCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddPredicate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddPredicate(KBPredicate pred) {
            this.Invoke("AddPredicate", new object[] {
                        pred});
        }
        
        /// <remarks/>
        public void AddPredicateAsync(KBPredicate pred) {
            this.AddPredicateAsync(pred, null);
        }
        
        /// <remarks/>
        public void AddPredicateAsync(KBPredicate pred, object userState) {
            if ((this.AddPredicateOperationCompleted == null)) {
                this.AddPredicateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPredicateOperationCompleted);
            }
            this.InvokeAsync("AddPredicate", new object[] {
                        pred}, this.AddPredicateOperationCompleted, userState);
        }
        
        private void OnAddPredicateOperationCompleted(object arg) {
            if ((this.AddPredicateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPredicateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewAlert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddNewAlert([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] msg) {
            this.Invoke("AddNewAlert", new object[] {
                        msg});
        }
        
        /// <remarks/>
        public void AddNewAlertAsync(byte[] msg) {
            this.AddNewAlertAsync(msg, null);
        }
        
        /// <remarks/>
        public void AddNewAlertAsync(byte[] msg, object userState) {
            if ((this.AddNewAlertOperationCompleted == null)) {
                this.AddNewAlertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewAlertOperationCompleted);
            }
            this.InvokeAsync("AddNewAlert", new object[] {
                        msg}, this.AddNewAlertOperationCompleted, userState);
        }
        
        private void OnAddNewAlertOperationCompleted(object arg) {
            if ((this.AddNewAlertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewAlertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vulnerability {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string severityField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KBImplication {
        
        private string implyingNameField;
        
        private string impliedNameField;
        
        private int numArgMapField;
        
        private int[] implyingArgField;
        
        private int[] impliedArgField;
        
        /// <remarks/>
        public string ImplyingName {
            get {
                return this.implyingNameField;
            }
            set {
                this.implyingNameField = value;
            }
        }
        
        /// <remarks/>
        public string ImpliedName {
            get {
                return this.impliedNameField;
            }
            set {
                this.impliedNameField = value;
            }
        }
        
        /// <remarks/>
        public int NumArgMap {
            get {
                return this.numArgMapField;
            }
            set {
                this.numArgMapField = value;
            }
        }
        
        /// <remarks/>
        public int[] ImplyingArg {
            get {
                return this.implyingArgField;
            }
            set {
                this.implyingArgField = value;
            }
        }
        
        /// <remarks/>
        public int[] ImpliedArg {
            get {
                return this.impliedArgField;
            }
            set {
                this.impliedArgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KBHyperAlertType {
        
        private string[] factsField;
        
        private KBPredicate[] prerequisitesField;
        
        private KBPredicate[] consequencesField;
        
        private string nameField;
        
        /// <remarks/>
        public string[] Facts {
            get {
                return this.factsField;
            }
            set {
                this.factsField = value;
            }
        }
        
        /// <remarks/>
        public KBPredicate[] Prerequisites {
            get {
                return this.prerequisitesField;
            }
            set {
                this.prerequisitesField = value;
            }
        }
        
        /// <remarks/>
        public KBPredicate[] Consequences {
            get {
                return this.consequencesField;
            }
            set {
                this.consequencesField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KBPredicate {
        
        private string predicateNameField;
        
        private int predicateIDField;
        
        private int numOfFactsField;
        
        private int[] argIDField;
        
        private int[] argPosField;
        
        private string[] argAttrField;
        
        /// <remarks/>
        public string PredicateName {
            get {
                return this.predicateNameField;
            }
            set {
                this.predicateNameField = value;
            }
        }
        
        /// <remarks/>
        public int PredicateID {
            get {
                return this.predicateIDField;
            }
            set {
                this.predicateIDField = value;
            }
        }
        
        /// <remarks/>
        public int NumOfFacts {
            get {
                return this.numOfFactsField;
            }
            set {
                this.numOfFactsField = value;
            }
        }
        
        /// <remarks/>
        public int[] ArgID {
            get {
                return this.argIDField;
            }
            set {
                this.argIDField = value;
            }
        }
        
        /// <remarks/>
        public int[] ArgPos {
            get {
                return this.argPosField;
            }
            set {
                this.argPosField = value;
            }
        }
        
        /// <remarks/>
        public string[] ArgAttr {
            get {
                return this.argAttrField;
            }
            set {
                this.argAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RawAlert {
        
        private string messageIDField;
        
        private string analyzerIDField;
        
        private string createTimeField;
        
        private string detectTimeField;
        
        private string sourceNetworkAddressField;
        
        private string sourcePortField;
        
        private string targetNetworkAddressField;
        
        private string targetPortField;
        
        private string assessmentImpactField;
        
        private string alertNameField;
        
        private string messageIDField1;
        
        private string analyzerIDField1;
        
        private string createTimeField1;
        
        private string detectTimeField1;
        
        private string sourceNetworkAddressField1;
        
        private string sourcePortField1;
        
        private string targetNetworkAddressField1;
        
        private string targetPortField1;
        
        private string assessmentImpactField1;
        
        private string alertNameField1;
        
        /// <remarks/>
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string analyzerID {
            get {
                return this.analyzerIDField;
            }
            set {
                this.analyzerIDField = value;
            }
        }
        
        /// <remarks/>
        public string createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string detectTime {
            get {
                return this.detectTimeField;
            }
            set {
                this.detectTimeField = value;
            }
        }
        
        /// <remarks/>
        public string sourceNetworkAddress {
            get {
                return this.sourceNetworkAddressField;
            }
            set {
                this.sourceNetworkAddressField = value;
            }
        }
        
        /// <remarks/>
        public string sourcePort {
            get {
                return this.sourcePortField;
            }
            set {
                this.sourcePortField = value;
            }
        }
        
        /// <remarks/>
        public string targetNetworkAddress {
            get {
                return this.targetNetworkAddressField;
            }
            set {
                this.targetNetworkAddressField = value;
            }
        }
        
        /// <remarks/>
        public string targetPort {
            get {
                return this.targetPortField;
            }
            set {
                this.targetPortField = value;
            }
        }
        
        /// <remarks/>
        public string assessmentImpact {
            get {
                return this.assessmentImpactField;
            }
            set {
                this.assessmentImpactField = value;
            }
        }
        
        /// <remarks/>
        public string alertName {
            get {
                return this.alertNameField;
            }
            set {
                this.alertNameField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField1;
            }
            set {
                this.messageIDField1 = value;
            }
        }
        
        /// <remarks/>
        public string AnalyzerID {
            get {
                return this.analyzerIDField1;
            }
            set {
                this.analyzerIDField1 = value;
            }
        }
        
        /// <remarks/>
        public string CreateTime {
            get {
                return this.createTimeField1;
            }
            set {
                this.createTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string DetectTime {
            get {
                return this.detectTimeField1;
            }
            set {
                this.detectTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string SourceNetworkAddress {
            get {
                return this.sourceNetworkAddressField1;
            }
            set {
                this.sourceNetworkAddressField1 = value;
            }
        }
        
        /// <remarks/>
        public string SourcePort {
            get {
                return this.sourcePortField1;
            }
            set {
                this.sourcePortField1 = value;
            }
        }
        
        /// <remarks/>
        public string TargetNetworkAddress {
            get {
                return this.targetNetworkAddressField1;
            }
            set {
                this.targetNetworkAddressField1 = value;
            }
        }
        
        /// <remarks/>
        public string TargetPort {
            get {
                return this.targetPortField1;
            }
            set {
                this.targetPortField1 = value;
            }
        }
        
        /// <remarks/>
        public string AssessmentImpact {
            get {
                return this.assessmentImpactField1;
            }
            set {
                this.assessmentImpactField1 = value;
            }
        }
        
        /// <remarks/>
        public string AlertName {
            get {
                return this.alertNameField1;
            }
            set {
                this.alertNameField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ScanServerVulnCompletedEventHandler(object sender, ScanServerVulnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScanServerVulnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ScanServerVulnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vulnerability[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vulnerability[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRawAlertsCompletedEventHandler(object sender, GetRawAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRawAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRawAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAlertsWithinIntervalCompletedEventHandler(object sender, GetAlertsWithinIntervalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAlertsWithinIntervalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAlertsWithinIntervalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServerNetworkTrafficCompletedEventHandler(object sender, GetServerNetworkTrafficCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServerNetworkTrafficCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServerNetworkTrafficCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetKBPredicatesCompletedEventHandler(object sender, GetKBPredicatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKBPredicatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKBPredicatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KBPredicate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KBPredicate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetKBHyperAlertTypesCompletedEventHandler(object sender, GetKBHyperAlertTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKBHyperAlertTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKBHyperAlertTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KBHyperAlertType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KBHyperAlertType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetKBImplicationsCompletedEventHandler(object sender, GetKBImplicationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKBImplicationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKBImplicationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KBImplication[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KBImplication[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetHyperAlertTypeCompletedEventHandler(object sender, GetHyperAlertTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHyperAlertTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHyperAlertTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KBHyperAlertType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KBHyperAlertType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddHyperAlertTypeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddImplicationCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddPredicateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddNewAlertCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591