//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace SecVizAdminApp.AggregationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AggregationServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AggregationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback NoneAggregateAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrivialAggregateAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback KmeanAggregationAlertsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DensityAggregationAlertsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AggregationService() {
            this.Url = global::SecVizAdminApp.Properties.Settings.Default.SecVizUserControl_AggregationService_AggregationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event NoneAggregateAlertsCompletedEventHandler NoneAggregateAlertsCompleted;
        
        /// <remarks/>
        public event TrivialAggregateAlertsCompletedEventHandler TrivialAggregateAlertsCompleted;
        
        /// <remarks/>
        public event KmeanAggregationAlertsCompletedEventHandler KmeanAggregationAlertsCompleted;
        
        /// <remarks/>
        public event DensityAggregationAlertsCompletedEventHandler DensityAggregationAlertsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NoneAggregateAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] NoneAggregateAlerts() {
            object[] results = this.Invoke("NoneAggregateAlerts", new object[0]);
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void NoneAggregateAlertsAsync() {
            this.NoneAggregateAlertsAsync(null);
        }
        
        /// <remarks/>
        public void NoneAggregateAlertsAsync(object userState) {
            if ((this.NoneAggregateAlertsOperationCompleted == null)) {
                this.NoneAggregateAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNoneAggregateAlertsOperationCompleted);
            }
            this.InvokeAsync("NoneAggregateAlerts", new object[0], this.NoneAggregateAlertsOperationCompleted, userState);
        }
        
        private void OnNoneAggregateAlertsOperationCompleted(object arg) {
            if ((this.NoneAggregateAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NoneAggregateAlertsCompleted(this, new NoneAggregateAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrivialAggregateAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] TrivialAggregateAlerts() {
            object[] results = this.Invoke("TrivialAggregateAlerts", new object[0]);
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void TrivialAggregateAlertsAsync() {
            this.TrivialAggregateAlertsAsync(null);
        }
        
        /// <remarks/>
        public void TrivialAggregateAlertsAsync(object userState) {
            if ((this.TrivialAggregateAlertsOperationCompleted == null)) {
                this.TrivialAggregateAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrivialAggregateAlertsOperationCompleted);
            }
            this.InvokeAsync("TrivialAggregateAlerts", new object[0], this.TrivialAggregateAlertsOperationCompleted, userState);
        }
        
        private void OnTrivialAggregateAlertsOperationCompleted(object arg) {
            if ((this.TrivialAggregateAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrivialAggregateAlertsCompleted(this, new TrivialAggregateAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KmeanAggregationAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] KmeanAggregationAlerts() {
            object[] results = this.Invoke("KmeanAggregationAlerts", new object[0]);
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void KmeanAggregationAlertsAsync() {
            this.KmeanAggregationAlertsAsync(null);
        }
        
        /// <remarks/>
        public void KmeanAggregationAlertsAsync(object userState) {
            if ((this.KmeanAggregationAlertsOperationCompleted == null)) {
                this.KmeanAggregationAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKmeanAggregationAlertsOperationCompleted);
            }
            this.InvokeAsync("KmeanAggregationAlerts", new object[0], this.KmeanAggregationAlertsOperationCompleted, userState);
        }
        
        private void OnKmeanAggregationAlertsOperationCompleted(object arg) {
            if ((this.KmeanAggregationAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KmeanAggregationAlertsCompleted(this, new KmeanAggregationAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DensityAggregationAlerts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RawAlert[] DensityAggregationAlerts() {
            object[] results = this.Invoke("DensityAggregationAlerts", new object[0]);
            return ((RawAlert[])(results[0]));
        }
        
        /// <remarks/>
        public void DensityAggregationAlertsAsync() {
            this.DensityAggregationAlertsAsync(null);
        }
        
        /// <remarks/>
        public void DensityAggregationAlertsAsync(object userState) {
            if ((this.DensityAggregationAlertsOperationCompleted == null)) {
                this.DensityAggregationAlertsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDensityAggregationAlertsOperationCompleted);
            }
            this.InvokeAsync("DensityAggregationAlerts", new object[0], this.DensityAggregationAlertsOperationCompleted, userState);
        }
        
        private void OnDensityAggregationAlertsOperationCompleted(object arg) {
            if ((this.DensityAggregationAlertsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DensityAggregationAlertsCompleted(this, new DensityAggregationAlertsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RawAlert {
        
        private string messageIDField;
        
        private string analyzerIDField;
        
        private string createTimeField;
        
        private string detectTimeField;
        
        private string sourceNetworkAddressField;
        
        private string sourcePortField;
        
        private string targetNetworkAddressField;
        
        private string targetPortField;
        
        private string assessmentImpactField;
        
        private string alertNameField;
        
        private string messageIDField1;
        
        private string analyzerIDField1;
        
        private string createTimeField1;
        
        private string detectTimeField1;
        
        private string sourceNetworkAddressField1;
        
        private string sourcePortField1;
        
        private string targetNetworkAddressField1;
        
        private string targetPortField1;
        
        private string assessmentImpactField1;
        
        private string alertNameField1;
        
        /// <remarks/>
        public string messageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string analyzerID {
            get {
                return this.analyzerIDField;
            }
            set {
                this.analyzerIDField = value;
            }
        }
        
        /// <remarks/>
        public string createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public string detectTime {
            get {
                return this.detectTimeField;
            }
            set {
                this.detectTimeField = value;
            }
        }
        
        /// <remarks/>
        public string sourceNetworkAddress {
            get {
                return this.sourceNetworkAddressField;
            }
            set {
                this.sourceNetworkAddressField = value;
            }
        }
        
        /// <remarks/>
        public string sourcePort {
            get {
                return this.sourcePortField;
            }
            set {
                this.sourcePortField = value;
            }
        }
        
        /// <remarks/>
        public string targetNetworkAddress {
            get {
                return this.targetNetworkAddressField;
            }
            set {
                this.targetNetworkAddressField = value;
            }
        }
        
        /// <remarks/>
        public string targetPort {
            get {
                return this.targetPortField;
            }
            set {
                this.targetPortField = value;
            }
        }
        
        /// <remarks/>
        public string assessmentImpact {
            get {
                return this.assessmentImpactField;
            }
            set {
                this.assessmentImpactField = value;
            }
        }
        
        /// <remarks/>
        public string alertName {
            get {
                return this.alertNameField;
            }
            set {
                this.alertNameField = value;
            }
        }
        
        /// <remarks/>
        public string MessageID {
            get {
                return this.messageIDField1;
            }
            set {
                this.messageIDField1 = value;
            }
        }
        
        /// <remarks/>
        public string AnalyzerID {
            get {
                return this.analyzerIDField1;
            }
            set {
                this.analyzerIDField1 = value;
            }
        }
        
        /// <remarks/>
        public string CreateTime {
            get {
                return this.createTimeField1;
            }
            set {
                this.createTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string DetectTime {
            get {
                return this.detectTimeField1;
            }
            set {
                this.detectTimeField1 = value;
            }
        }
        
        /// <remarks/>
        public string SourceNetworkAddress {
            get {
                return this.sourceNetworkAddressField1;
            }
            set {
                this.sourceNetworkAddressField1 = value;
            }
        }
        
        /// <remarks/>
        public string SourcePort {
            get {
                return this.sourcePortField1;
            }
            set {
                this.sourcePortField1 = value;
            }
        }
        
        /// <remarks/>
        public string TargetNetworkAddress {
            get {
                return this.targetNetworkAddressField1;
            }
            set {
                this.targetNetworkAddressField1 = value;
            }
        }
        
        /// <remarks/>
        public string TargetPort {
            get {
                return this.targetPortField1;
            }
            set {
                this.targetPortField1 = value;
            }
        }
        
        /// <remarks/>
        public string AssessmentImpact {
            get {
                return this.assessmentImpactField1;
            }
            set {
                this.assessmentImpactField1 = value;
            }
        }
        
        /// <remarks/>
        public string AlertName {
            get {
                return this.alertNameField1;
            }
            set {
                this.alertNameField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void NoneAggregateAlertsCompletedEventHandler(object sender, NoneAggregateAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoneAggregateAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NoneAggregateAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TrivialAggregateAlertsCompletedEventHandler(object sender, TrivialAggregateAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrivialAggregateAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrivialAggregateAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void KmeanAggregationAlertsCompletedEventHandler(object sender, KmeanAggregationAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KmeanAggregationAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KmeanAggregationAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DensityAggregationAlertsCompletedEventHandler(object sender, DensityAggregationAlertsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DensityAggregationAlertsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DensityAggregationAlertsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RawAlert[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RawAlert[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591